/*
 * Plisio API
 * Plisio payment gateway API
 *
 * OpenAPI spec version: 1.0
 * Contact: lead@plisio.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plisio.api;

import com.plisio.model.BalanceApiResponseDto;
import com.plisio.model.ErrorResponseDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BalanceApi
 */
@Ignore
public class BalanceApiTest {

    private final BalanceApi api = new BalanceApi();

    /**
     * Get cryptocurrency balance
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void balancesPsysCidGetTest() {
        String psysCid = null;
        BalanceApiResponseDto response = api.balancesPsysCidGet(psysCid);

        // TODO: test validations
    }
}
