/*
 * Plisio API
 * Plisio payment gateway API
 *
 * OpenAPI spec version: 1.0
 * Contact: lead@plisio.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plisio.api;

import com.plisio.model.CryptocurrencyApiResponseDto;
import com.plisio.model.ErrorResponseDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CurrenciesApi
 */
@Ignore
public class CurrenciesApiTest {

    private final CurrenciesApi api = new CurrenciesApi();

    /**
     * List of supported cryptocurrencies
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currenciesFiatGetTest() {
        String fiat = null;
        CryptocurrencyApiResponseDto response = api.currenciesFiatGet(fiat);

        // TODO: test validations
    }
}
