/*
 * Plisio API
 * Plisio payment gateway API
 *
 * OpenAPI spec version: 1.0
 * Contact: lead@plisio.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plisio.api;

import com.plisio.model.ErrorResponseDto;
import com.plisio.model.ShopResponseDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ShopApi
 */
@Ignore
public class ShopApiTest {

    private final ShopApi api = new ShopApi();

    /**
     * Get shop info by api_key
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void shopsGetTest() {
        ShopResponseDto response = api.shopsGet();

        // TODO: test validations
    }
}
