/*
 * Plisio API
 * Plisio payment gateway API
 *
 * OpenAPI spec version: 1.0
 * Contact: lead@plisio.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plisio.api;

import com.plisio.model.ErrorResponseDto;
import com.plisio.model.WithdrawApiResponseDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WithdrawApi
 */
@Ignore
public class WithdrawApiTest {

    private final WithdrawApi api = new WithdrawApi();

    /**
     * Create new invoice
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void operationsWithdrawGetTest() {
        String psysCid = null;
        String to = null;
        String amount = null;
        String type = null;
        String feePlan = null;
        WithdrawApiResponseDto response = api.operationsWithdrawGet(psysCid, to, amount, type, feePlan);

        // TODO: test validations
    }
}
