/*
 * Plisio API
 * Plisio payment gateway API
 *
 * OpenAPI spec version: 1.0
 * Contact: lead@plisio.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plisio.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.plisio.model.FeePlanCommonDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * FeePlanTonDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-10-04T15:20:38.886999298+03:00[Europe/Moscow]")

public class FeePlanTonDto extends FeePlanCommonDto {
  @JsonProperty("value")
  private BigDecimal value = null;

  @JsonProperty("feeUnit")
  private BigDecimal feeUnit = null;

  public FeePlanTonDto value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * Fee value
   * @return value
  **/
  @Schema(description = "Fee value")
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }

  public FeePlanTonDto feeUnit(BigDecimal feeUnit) {
    this.feeUnit = feeUnit;
    return this;
  }

   /**
   * Fee unit
   * @return feeUnit
  **/
  @Schema(description = "Fee unit")
  public BigDecimal getFeeUnit() {
    return feeUnit;
  }

  public void setFeeUnit(BigDecimal feeUnit) {
    this.feeUnit = feeUnit;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeePlanTonDto feePlanTonDto = (FeePlanTonDto) o;
    return Objects.equals(this.value, feePlanTonDto.value) &&
        Objects.equals(this.feeUnit, feePlanTonDto.feeUnit) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, feeUnit, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeePlanTonDto {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    feeUnit: ").append(toIndentedString(feeUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
