/*
 * Plisio API
 * Plisio payment gateway API
 *
 * OpenAPI spec version: 1.0
 * Contact: lead@plisio.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plisio.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
/**
 * FeePlanLimitsEthDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-10-04T15:20:38.886999298+03:00[Europe/Moscow]")

public class FeePlanLimitsEthDto {
  @JsonProperty("plan")
  private String plan = null;

  @JsonProperty("value")
  private String value = null;

  @JsonProperty("unit")
  private BigDecimal unit = null;

  @JsonProperty("gasLimit")
  private Integer gasLimit = null;

  @JsonProperty("gasPrice")
  private Integer gasPrice = null;

  @JsonProperty("dynamicValues")
  private String dynamicValues = null;

  public FeePlanLimitsEthDto plan(String plan) {
    this.plan = plan;
    return this;
  }

   /**
   * Plan name: normal, priority or custom
   * @return plan
  **/
  @Schema(description = "Plan name: normal, priority or custom")
  public String getPlan() {
    return plan;
  }

  public void setPlan(String plan) {
    this.plan = plan;
  }

  public FeePlanLimitsEthDto value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Fee value
   * @return value
  **/
  @Schema(description = "Fee value")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public FeePlanLimitsEthDto unit(BigDecimal unit) {
    this.unit = unit;
    return this;
  }

   /**
   * Fee unit
   * @return unit
  **/
  @Schema(description = "Fee unit")
  public BigDecimal getUnit() {
    return unit;
  }

  public void setUnit(BigDecimal unit) {
    this.unit = unit;
  }

  public FeePlanLimitsEthDto gasLimit(Integer gasLimit) {
    this.gasLimit = gasLimit;
    return this;
  }

   /**
   * Ethereum gas limit
   * @return gasLimit
  **/
  @Schema(description = "Ethereum gas limit")
  public Integer getGasLimit() {
    return gasLimit;
  }

  public void setGasLimit(Integer gasLimit) {
    this.gasLimit = gasLimit;
  }

  public FeePlanLimitsEthDto gasPrice(Integer gasPrice) {
    this.gasPrice = gasPrice;
    return this;
  }

   /**
   * Ethereum gas price in Gwai
   * @return gasPrice
  **/
  @Schema(description = "Ethereum gas price in Gwai")
  public Integer getGasPrice() {
    return gasPrice;
  }

  public void setGasPrice(Integer gasPrice) {
    this.gasPrice = gasPrice;
  }

  public FeePlanLimitsEthDto dynamicValues(String dynamicValues) {
    this.dynamicValues = dynamicValues;
    return this;
  }

   /**
   * Name of dynamic property name (ex: gasPrice)
   * @return dynamicValues
  **/
  @Schema(description = "Name of dynamic property name (ex: gasPrice)")
  public String getDynamicValues() {
    return dynamicValues;
  }

  public void setDynamicValues(String dynamicValues) {
    this.dynamicValues = dynamicValues;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FeePlanLimitsEthDto feePlanLimitsEthDto = (FeePlanLimitsEthDto) o;
    return Objects.equals(this.plan, feePlanLimitsEthDto.plan) &&
        Objects.equals(this.value, feePlanLimitsEthDto.value) &&
        Objects.equals(this.unit, feePlanLimitsEthDto.unit) &&
        Objects.equals(this.gasLimit, feePlanLimitsEthDto.gasLimit) &&
        Objects.equals(this.gasPrice, feePlanLimitsEthDto.gasPrice) &&
        Objects.equals(this.dynamicValues, feePlanLimitsEthDto.dynamicValues);
  }

  @Override
  public int hashCode() {
    return Objects.hash(plan, value, unit, gasLimit, gasPrice, dynamicValues);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FeePlanLimitsEthDto {\n");
    
    sb.append("    plan: ").append(toIndentedString(plan)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    unit: ").append(toIndentedString(unit)).append("\n");
    sb.append("    gasLimit: ").append(toIndentedString(gasLimit)).append("\n");
    sb.append("    gasPrice: ").append(toIndentedString(gasPrice)).append("\n");
    sb.append("    dynamicValues: ").append(toIndentedString(dynamicValues)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
