/*
 * Plisio API
 * Plisio payment gateway API
 *
 * OpenAPI spec version: 1.0
 * Contact: lead@plisio.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plisio.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.plisio.model.InvoicePaysysDto;
import io.swagger.v3.oas.annotations.media.Schema;
/**
 * InvoicePaysysContractsGroupDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-10-04T15:20:38.886999298+03:00[Europe/Moscow]")

public class InvoicePaysysContractsGroupDto extends InvoicePaysysDto {
  @JsonProperty("contractGroupCid")
  private String contractGroupCid = null;

  @JsonProperty("contractGroupIcon")
  private String contractGroupIcon = null;

  @JsonProperty("contractGroupName")
  private String contractGroupName = null;

  public InvoicePaysysContractsGroupDto contractGroupCid(String contractGroupCid) {
    this.contractGroupCid = contractGroupCid;
    return this;
  }

   /**
   * Contract group cid
   * @return contractGroupCid
  **/
  @Schema(description = "Contract group cid")
  public String getContractGroupCid() {
    return contractGroupCid;
  }

  public void setContractGroupCid(String contractGroupCid) {
    this.contractGroupCid = contractGroupCid;
  }

  public InvoicePaysysContractsGroupDto contractGroupIcon(String contractGroupIcon) {
    this.contractGroupIcon = contractGroupIcon;
    return this;
  }

   /**
   * Contract group icon
   * @return contractGroupIcon
  **/
  @Schema(description = "Contract group icon")
  public String getContractGroupIcon() {
    return contractGroupIcon;
  }

  public void setContractGroupIcon(String contractGroupIcon) {
    this.contractGroupIcon = contractGroupIcon;
  }

  public InvoicePaysysContractsGroupDto contractGroupName(String contractGroupName) {
    this.contractGroupName = contractGroupName;
    return this;
  }

   /**
   * Contract group name
   * @return contractGroupName
  **/
  @Schema(description = "Contract group name")
  public String getContractGroupName() {
    return contractGroupName;
  }

  public void setContractGroupName(String contractGroupName) {
    this.contractGroupName = contractGroupName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoicePaysysContractsGroupDto invoicePaysysContractsGroupDto = (InvoicePaysysContractsGroupDto) o;
    return Objects.equals(this.contractGroupCid, invoicePaysysContractsGroupDto.contractGroupCid) &&
        Objects.equals(this.contractGroupIcon, invoicePaysysContractsGroupDto.contractGroupIcon) &&
        Objects.equals(this.contractGroupName, invoicePaysysContractsGroupDto.contractGroupName) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractGroupCid, contractGroupIcon, contractGroupName, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoicePaysysContractsGroupDto {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    contractGroupCid: ").append(toIndentedString(contractGroupCid)).append("\n");
    sb.append("    contractGroupIcon: ").append(toIndentedString(contractGroupIcon)).append("\n");
    sb.append("    contractGroupName: ").append(toIndentedString(contractGroupName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
