/*
 * Plisio API
 * Plisio payment gateway API
 *
 * OpenAPI spec version: 1.0
 * Contact: lead@plisio.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.plisio.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.plisio.model.HateoasLinksDto;
import com.plisio.model.HateoasMetaDto;
import com.plisio.model.OperationDto;
import com.plisio.model.SuccessResponseDto;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
/**
 * OperationsHateoasResponseDto
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-10-04T15:20:38.886999298+03:00[Europe/Moscow]")

public class OperationsHateoasResponseDto extends SuccessResponseDto {
  @JsonProperty("operations")
  private List<OperationDto> operations = null;

  @JsonProperty("_links")
  private HateoasLinksDto _links = null;

  @JsonProperty("_meta")
  private HateoasMetaDto _meta = null;

  public OperationsHateoasResponseDto operations(List<OperationDto> operations) {
    this.operations = operations;
    return this;
  }

  public OperationsHateoasResponseDto addOperationsItem(OperationDto operationsItem) {
    if (this.operations == null) {
      this.operations = new ArrayList<OperationDto>();
    }
    this.operations.add(operationsItem);
    return this;
  }

   /**
   * Get operations
   * @return operations
  **/
  @Schema(description = "")
  public List<OperationDto> getOperations() {
    return operations;
  }

  public void setOperations(List<OperationDto> operations) {
    this.operations = operations;
  }

  public OperationsHateoasResponseDto _links(HateoasLinksDto _links) {
    this._links = _links;
    return this;
  }

   /**
   * Get _links
   * @return _links
  **/
  @Schema(description = "")
  public HateoasLinksDto getLinks() {
    return _links;
  }

  public void setLinks(HateoasLinksDto _links) {
    this._links = _links;
  }

  public OperationsHateoasResponseDto _meta(HateoasMetaDto _meta) {
    this._meta = _meta;
    return this;
  }

   /**
   * Get _meta
   * @return _meta
  **/
  @Schema(description = "")
  public HateoasMetaDto getMeta() {
    return _meta;
  }

  public void setMeta(HateoasMetaDto _meta) {
    this._meta = _meta;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OperationsHateoasResponseDto operationsHateoasResponseDto = (OperationsHateoasResponseDto) o;
    return Objects.equals(this.operations, operationsHateoasResponseDto.operations) &&
        Objects.equals(this._links, operationsHateoasResponseDto._links) &&
        Objects.equals(this._meta, operationsHateoasResponseDto._meta) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operations, _links, _meta, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OperationsHateoasResponseDto {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    _links: ").append(toIndentedString(_links)).append("\n");
    sb.append("    _meta: ").append(toIndentedString(_meta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
